version: 0.2

env:
  variables:
    DB_PORT: 3306
    RACK_ENV: "production"
    ENV: ${ENV}
    BUNDLE_WITHOUT: "test development"
  parameter-store:
    REGISTRY_URL: "/moj-network-access-control/$ENV/admin/ecr/endpoint"
    TERRAFORM_OUTPUTS: "/moj-network-access-control/terraform/$ENV/outputs"
    TARGET_AWS_ACCOUNT_ID: "/codebuild/$ENV/account_id"
    ROLE_ARN: "/codebuild/pttp-ci-infrastructure-core-pipeline/${ENV}/assume_role"
    DOCKER_USERNAME: "/moj-network-access-control/docker/username"
    DOCKER_PASSWORD: "/moj-network-access-control/docker/password"

phases:
  build:
    commands:
      - make authenticate-docker
      - make publish
      - make migrate
      - make bootstrap
      - make deploy
