version: 0.2

env:
  variables:
    AWS_REGION: eu-west-2
    ENV: test
    RACK_ENV: test
  parameter-store:
    DOCKER_USERNAME: "/moj-network-access-control/docker/username"
    DOCKER_PASSWORD: "/moj-network-access-control/docker/password"

phases:
  install:
    commands:
      - echo none

  build:
    commands:
      - GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id pttp-ci-infrastructure__github_token --region eu-west-2 --query SecretString --output text | jq -r .token)
      - make authenticate-docker
      - ENV=test make db-setup
      - make test
      - make integration-test-schema-private GITHUB_TOKEN=$GITHUB_TOKEN
