version: 0.2

env:
  variables:
    AWS_REGION: eu-west-2
    ENV: test
    RACK_ENV: test
  parameter-store:
    DOCKER_USERNAME: "/moj-network-access-control/docker/username"
    DOCKER_PASSWORD: "/moj-network-access-control/docker/password"

phases:
  install:
    commands:
      - echo none

  build:
    commands:
      - make authenticate-docker
      - ENV=test make db-setup
      - make test
      - make integration-test-schema
