version: "3.4"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    env_file: .env.${ENV}
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - datavolume:/var/lib/mysql
    networks:
      - adminnet
    command: "--default-authentication-plugin=caching_sha2_password"

  app:
    build:
      context: .
      args:
        UID: "${UID}"
        BUNDLE_INSTALL_FLAGS: "${BUNDLE_INSTALL_FLAGS:- --jobs 20 --retry 5 --full-index}"
    user: "${UID}:${UID}"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/home/app/moj-network-access-admin
      - node_modules:/home/app/moj-network-access-admin/node_modules
    links:
      - db
    expose:
      - "3000"
    ports:
      - "3000:3000"
    env_file: .env.${ENV}
    networks:
      - adminnet

  background_worker:
    build:
      context: .
      args:
        UID: "${UID}"
        BUNDLE_INSTALL_FLAGS: "${BUNDLE_INSTALL_FLAGS:- --jobs 20 --retry 5}"
    user: "${UID}:${UID}"
    command: bash -c "bundle exec rake jobs:work"
    volumes:
      - .:/home/app/moj-network-access-admin
      - node_modules:/home/app/moj-network-access-admin/node_modules
    links:
      - db
    env_file: .env.${ENV}
    networks:
      - adminnet

volumes:
  node_modules:
  datavolume:

networks:
  adminnet:
    name: adminnet
