module AttributesHelper
  def self.requests
    %w(
      User-Name
      User-Password
      CHAP-Password
      NAS-IP-Address
      NAS-Port
      Service-Type
      Framed-Protocol
      Framed-IP-Address
      Framed-IP-Netmask
      Framed-Routing
      Filter-Id
      Framed-MTU
      Framed-Compression
      Login-IP-Host
      Login-Service
      Login-TCP-Port
      Reply-Message
      Callback-Number
      Callback-Id
      Framed-Route
      Framed-IPX-Network
      State
      Class
      Vendor-Specific
      Session-Timeout
      Idle-Timeout
      Termination-Action
      Called-Station-Id
      Calling-Station-Id
      NAS-Identifier
      Proxy-State
      Login-LAT-Service
      Login-LAT-Node
      Login-LAT-Group
      Framed-AppleTalk-Link
      Framed-AppleTalk-Network
      Framed-AppleTalk-Zone
      CHAP-Challenge
      NAS-Port-Type
      Port-Limit
      Login-LAT-Port
      Port-Limit
      Login-LAT-Port
      TLS-Cert-Serial
      TLS-Cert-Expiration
      TLS-Cert-Issuer
      TLS-Cert-Subject
      TLS-Cert-Common-Name
      TLS-Cert-Subject-Alt-Name-Email
      TLS-Cert-Subject-Alt-Name-Dns
      TLS-Cert-Subject-Alt-Name-Upn
      TLS-Client-Cert-Serial
      TLS-Client-Cert-Expiration
      TLS-Client-Cert-Issuer
      TLS-Client-Cert-Subject
      TLS-Client-Cert-Common-Name
      TLS-Client-Cert-Filename
      TLS-Client-Cert-Subject-Alt-Name-Email
      TLS-Client-Cert-X509v3-Extended-Key-Usage
      TLS-Client-Cert-X509v
    )
  end
end
