module AttributesHelper
  def self.requests
    %w[
      User-Name
      User-Password
      CHAP-Password
      NAS-IP-Address
      NAS-Port
      Service-Type
      Framed-Protocol
      Framed-IP-Address
      Framed-IP-Netmask
      Framed-Routing
      Filter-Id
      Framed-MTU
      Framed-Compression
      Login-IP-Host
      Login-Service
      Login-TCP-Port
      Reply-Message
      Callback-Number
      Callback-Id
      Framed-Route
      Framed-IPX-Network
      State
      Class
      Vendor-Specific
      Session-Timeout
      Idle-Timeout
      Termination-Action
      Called-Station-Id
      Calling-Station-Id
      NAS-Identifier
      Proxy-State
      Login-LAT-Service
      Login-LAT-Node
      Login-LAT-Group
      Framed-AppleTalk-Link
      Framed-AppleTalk-Network
      Framed-AppleTalk-Zone
      CHAP-Challenge
      NAS-Port-Type
      Port-Limit
      Login-LAT-Port
      Port-Limit
      Login-LAT-Port
      TLS-Cert-Serial
      TLS-Cert-Expiration
      TLS-Cert-Issuer
      TLS-Cert-Subject
      TLS-Cert-Common-Name
      TLS-Cert-Subject-Alt-Name-Email
      TLS-Cert-Subject-Alt-Name-Dns
      TLS-Cert-Subject-Alt-Name-Upn
      TLS-Client-Cert-Serial
      TLS-Client-Cert-Expiration
      TLS-Client-Cert-Issuer
      TLS-Client-Cert-Subject
      TLS-Client-Cert-Common-Name
      TLS-Client-Cert-Filename
      TLS-Client-Cert-Subject-Alt-Name-Email
      TLS-Client-Cert-X509v3-Extended-Key-Usage
      TLS-Client-Cert-X509v
    ]
  end

  def self.responses
    %w[
      ARAP-Challenge-Response
      ARAP-Features
      ARAP-Password
      ARAP-Security
      ARAP-Security-Data
      ARAP-Zone-Access
      AUTH-Key
      Access-Accept
      Access-Challenge
      Access-Reject
      Access-Request
      Accounting-Request
      Accounting-Response
      Acct-Authentic
      Acct-Delay-Time
      Acct-Input-Gigawords
      Acct-Input-Octets
      Acct-Input-Packets
      Acct-Interim-Interval
      Acct-Link-Count
      Acct-Multi-Session-Id
      Acct-Output-Gigawords
      Acct-Output-Octets
      Acct-Output-Packets
      Acct-Session-Id
      Acct-Session-Time
      Acct-Status-Type
      Acct-Terminate-Cause
      Acct-Tunnel-Connection
      Acct-Tunnel-Packets-Lost
      CHAP-Challenge
      CHAP-Password
      Callback-Id
      Callback-Number
      Called-Station-Id
      Calling-Station-Id
      Change-of-Authorization
      Chargeable-User-Identity
      Class
      Configuration-Token
      Connect-Info
      DNS-Server-IPv6-Address
      DS-Lite
      DS-Lite-Tunnel-Name
      Delegated-IPv6-Prefix
      Delegated-IPv6-Prefix-Pool
      Digest-AKA-Auts
      Digest-Algorithm
      Digest-Auth-Param
      Digest-CNonce
      Digest-Domain
      Digest-Entity-Body-Hash
      Digest-HA1
      Digest-Method
      Digest-Nextnonce
      Digest-Nonce
      Digest-Nonce-Count
      Digest-Opaque
      Digest-Qop
      Digest-Realm
      Digest-Response
      Digest-Response-Auth
      Digest-Stale
      Digest-URI
      Digest-Username
      EAP-Message
      Error-Cause
      Event-Timestamp
      Extended-Type-1
      Extended-Type-2
      Extended-Type-3
      Extended-Type-4
      Extended-Vendor-Specific-1
      Extended-Vendor-Specific-2
      Extended-Vendor-Specific-3
      Extended-Vendor-Specific-4
      Extended-Vendor-Specific-5
      Extended-Vendor-Specific-6
      Filter-ID
      Filter-Id
      Framed-AppleTalk-Link
      Framed-AppleTalk-Network
      Framed-AppleTalk-Zone
      Framed-Compression
      Framed-IP-Address
      Framed-IP-Netmask
      Framed-IPX-Network
      Framed-IPv6-Address
      Framed-IPv6-Pool
      Framed-IPv6-Prefix
      Framed-IPv6-Route
      Framed-Interface-Id
      Framed-MTU
      Framed-Management-Protocol
      Framed-Pool
      Framed-Protocol
      Framed-Route
      Framed-Routing
      Idle-Timeout
      Keep-Alives
      Login-IP-Host
      Login-IPv6-Host
      Login-LAT-Group
      Login-LAT-Node
      Login-LAT-Port
      Login-LAT-Service
      Login-Service
      Login-TCP-Port
      Long-Extended-Type-1
      Long-Extended-Type-2
      MS-ARAP-Challenge
      MS-ARAP-Password-Change-Reason
      MS-Acct-Auth-Type
      MS-Acct-EAP-Type
      MS-BAP-Usage
      MS-CHAP-CPW-1
      MS-CHAP-CPW-2
      MS-CHAP-Challenge
      MS-CHAP-Domain
      MS-CHAP-Error
      MS-CHAP-LM-Enc-PW
      MS-CHAP-MPPE-Keys
      MS-CHAP-NT-Enc-PW
      MS-CHAP-Response
      MS-CHAP2-CPW
      MS-CHAP2-Response
      MS-CHAP2-Success
      MS-Filter
      MS-Link-Drop-Time-Limit
      MS-Link-Utilization-Threshold
      MS-MPPE-Encryption-Policy
      MS-MPPE-Encryption-Types
      MS-MPPE-Recv-Key
      MS-MPPE-Send-Key
      MS-New-ARAP-Password
      MS-Old-ARAP-Password
      MS-Primary-DNS-Server
      MS-Primary-NBNS-Server
      MS-RAS-Vendor
      MS-RAS-Version
      MS-Secondary-DNS-Server
      MS-Secondary-NBNS-Server
      Management-Policy-Id
      Management-Privilege-Level
      Management-Transport-Protection
      Message-Authenticator
      Mobile-Node-Identifier
      NAS-Filter-Rule
      NAS-IP-Address
      NAS-IPv6-Address
      NAS-Identifier
      NAS-Port
      NAS-Port-Id
      NAS-Port-Type
      PKM-AUTH-Key
      PKM-CA-Cert
      PKM-Config-Settings
      PKM-Cryptosuite-List
      PKM-SA-Descriptor
      PKM-SAID
      PKM-SS-Cert
      Password-Retry
      Port-Limit
      Proxy-State
      Reply-Message
      Route-IPv6-Information
      SIP-AOR
      Service-Selection
      Service-Type
      Session-Timeout
      State
      Stateful-IPv6-Address-Pool
      Termination-Action
      Tunnel-Assignment-ID
      Tunnel-Client-Auth-ID
      Tunnel-Client-Endpoint
      Tunnel-Link-Reject
      Tunnel-Link-Start
      Tunnel-Link-Stop
      Tunnel-Medium-Type
      Tunnel-Password
      Tunnel-Preference
      Tunnel-Private-Group-ID
      Tunnel-Reject
      Tunnel-Server-Auth-ID
      Tunnel-Server-Endpoint
      Tunnel-Start
      Tunnel-Stop
      Tunnel-Type
      User-Name
      User-Password
      Vendor-Id
      Vendor-Specific
    ]
  end
end
